// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoNT.Context;

namespace ProyectoNT.Migrations
{
    [DbContext(typeof(ClasesParticularesDatabaseContext))]
    [Migration("20211104003259_ProyectoNT.Context.ClasesParticularesDatabaseContext")]
    partial class ProyectoNTContextClasesParticularesDatabaseContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoNT.Models.Alumno", b =>
                {
                    b.Property<int>("idAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("escuela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("grado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAlumno");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ProyectoNT.Models.Clase", b =>
                {
                    b.Property<int>("idClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("alumnoidAlumno")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaYHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("idAlumno")
                        .HasColumnType("int");

                    b.Property<int>("idMateria")
                        .HasColumnType("int");

                    b.Property<int?>("materiaidMateria")
                        .HasColumnType("int");

                    b.Property<string>("tema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idClase");

                    b.HasIndex("alumnoidAlumno");

                    b.HasIndex("materiaidMateria");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("ProyectoNT.Models.Docente", b =>
                {
                    b.Property<int>("idDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDocente");

                    b.ToTable("Docente");
                });

            modelBuilder.Entity("ProyectoNT.Models.Materia", b =>
                {
                    b.Property<int>("idMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DocenteidDocente")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMateria");

                    b.HasIndex("DocenteidDocente");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ProyectoNT.Models.Clase", b =>
                {
                    b.HasOne("ProyectoNT.Models.Alumno", "alumno")
                        .WithMany()
                        .HasForeignKey("alumnoidAlumno");

                    b.HasOne("ProyectoNT.Models.Materia", "materia")
                        .WithMany()
                        .HasForeignKey("materiaidMateria");
                });

            modelBuilder.Entity("ProyectoNT.Models.Materia", b =>
                {
                    b.HasOne("ProyectoNT.Models.Docente", null)
                        .WithMany("materias")
                        .HasForeignKey("DocenteidDocente");
                });
#pragma warning restore 612, 618
        }
    }
}
